require 'nokogiri'
require 'open-uri'
require 'net/http'
require 'json'
require 'pry'

require_relative '../lib/scraper.rb'
require_relative '../lib/players.rb'
require_relative '../lib/teams.rb'
require_relative '../lib/cli.rb'